module.exports = {
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGIN_FAILURE: 'USER_LOGIN_FAILURE',
  USER_LOGIN_ERROR_SET: 'USER_LOGIN_ERROR_SET',
  USER_LOGIN_ERROR_CLEAN_UP: 'USER_LOGIN_ERROR_CLEAN_UP',
  USER_LOGGING_IN: 'USER_LOGGING_IN',
};
